Update terraform module with custom_route_table_name
Azure/terraform-azurerm-hubnetworking pull request #38
Opened 2023-06-16 06:54 UTC by chinthakaru

## Describe your changes
Updated the variables.tf, main.tf and main.tf within the examples folder to add the Custom route table name functionality. 
## Issue number

#000

## Checklist before requesting a review
- [ ] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [ ] I have executed pre-commit on my machine
- [ ] I have passed pr-check on my machine

Thanks for your cooperation!

2023-06-19 08:25 UTC, matt-FFFFFF requested changes

2023-06-19 18:24 UTC, matt-FFFFFF requested changes

2023-06-19 18:24 UTC, matt-FFFFFF commented on main.tf
> +  name                          = coalesce(var.hub_virtual_networks[each.key].route_table_name, "${each.key}-rt")
Sorry I meant like this, so as to align with CAF naming

```suggestion
  name                          = coalesce(var.hub_virtual_networks[each.key].route_table_name, "route-${each.key}")
```

2023-06-20 05:22 UTC, chinthakaru commented on main.tf
> +  name                          = coalesce(var.hub_virtual_networks[each.key].route_table_name, "${each.key}-rt")
Updated with the requested changes. Added default route table name according to the CAF naming reference.

2023-06-21 16:24 UTC, matt-FFFFFF commented
supersceded by #39

2023-06-21 16:24 UTC, closed without merging